about_v1
KulykAlexander/bandera-teams pull request #10
Opened 2022-09-17 18:12 UTC by Allmaren

V1

2022-09-17 19:03 UTC, KulykAlexander commented on src/partials/about.html
> +            media="(max-width:467px)" />
media="(max-width:767px)"

2022-09-17 19:11 UTC, Allmaren commented on src/partials/about.html
> +            media="(max-width:467px)" />
виправила. Дякую

2022-09-17 19:27 UTC, KulykAlexander requested changes
1. Html строка 25 здається має бути media="(max-width:767px)";
2. Замість формату .png  можливо краще .jpg;
3. Звідкись з’явились зайві файли index.css та  index.map.css, мабуть запускали компілятор.

2022-09-17 19:27 UTC, KulykAlexander commented on src/partials/about.html
> +            media="(max-width:467px)" />
media="(max-width:767px)"

2022-09-17 20:05 UTC, KulykAlexander approved these changes

2022-09-17 20:05 UTC, merged

2022-09-19 20:06 UTC, Allmaren commented
v2